/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#000000",
        "on-secondary": "#0b5800",
        "surface-bright": "#252b3f",
        "tertiary-fixed": "#ffd709",
        "on-tertiary-fixed": "#453900",
        "on-secondary-fixed": "#064200",
        "primary-dim": "#9c42f4",
        "outline-variant": "#444756",
        "tertiary": "#ffe792",
        "background": "#0a0e1a",
        "inverse-surface": "#faf8ff",
        "surface-container-lowest": "#000000",
        "on-primary-fixed-variant": "#420078",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "tertiary-dim": "#efc900",
        "on-background": "#e2e4f6",
        "on-primary-container": "#350062",
        "secondary-fixed-dim": "#2be800",
        "surface": "#0a0e1a",
        "inverse-on-surface": "#515463",
        "inverse-primary": "#8523dd",
        "surface-container": "#141928",
        "surface-container-highest": "#202537",
        "secondary-dim": "#2be800",
        "surface-variant": "#202537",
        "surface-container-low": "#0e1320",
        "surface-tint": "#ca98ff",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#0d6200",
        "on-primary": "#46007d",
        "on-surface": "#e2e4f6",
        "outline": "#717584",
        "primary-fixed": "#c185ff",
        "on-tertiary-container": "#5b4b00",
        "primary-fixed-dim": "#b772ff",
        "secondary-fixed": "#2ff801",
        "primary": "#ca98ff",
        "on-error-container": "#ffb2b9",
        "secondary": "#2ff801",
        "on-tertiary": "#655400",
        "surface-dim": "#0a0e1a",
        "tertiary-fixed-dim": "#efc900",
        "on-secondary-container": "#e7ffd9",
        "tertiary-container": "#ffd709",
        "error": "#ff6e84",
        "primary-container": "#c185ff",
        "on-surface-variant": "#a7aabb",
        "on-tertiary-fixed-variant": "#665500",
        "surface-container-high": "#1a1f2f",
        "secondary-container": "#106e00"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}